import type { SpeakerId, SpeakerProfile } from "../types";

export const speakerProfiles: Record<SpeakerId, SpeakerProfile> = {
  narrator: {
    id: "narrator",
    name: "环境",
    side: "none",
    themeColor: "#b9a87b",
    portraits: {},
    defaultPortrait: "",
  },
  zhaoying: {
    id: "zhaoying",
    name: "我",
    side: "left",
    themeColor: "#d7c99e",
    voiceId: "zh-CN-Xiaochen:DragonHDLatestNeural",
    portraits: {
      calm: "/media/portraits/zhaoying-calm.webp",
      guarded: "/media/portraits/zhaoying-guarded.webp",
      alarmed: "/media/portraits/zhaoying-alarmed.webp",
    },
    defaultPortrait: "calm",
  },
  "young-zhaoying": {
    id: "young-zhaoying",
    name: "年轻赵映",
    side: "left",
    themeColor: "#d7c99e",
    voiceId: "zh-CN-Xiaochen:DragonHDLatestNeural",
    portraits: {
      calm: "/media/portraits/zhaoying-calm.webp",
      guarded: "/media/portraits/zhaoying-guarded.webp",
      alarmed: "/media/portraits/zhaoying-alarmed.webp",
    },
    defaultPortrait: "guarded",
  },
  master: {
    id: "master",
    name: "沈老爷",
    side: "right",
    themeColor: "#b8a782",
    portraits: {},
    defaultPortrait: "",
  },
  steward: {
    id: "steward",
    name: "老周",
    side: "right",
    themeColor: "#b79a66",
    voiceId: "zh-CN-YunyangNeural",
    portraits: {
      courteous: "/media/portraits/steward-courteous.webp",
      knowing: "/media/portraits/steward-knowing.webp",
      guilty: "/media/portraits/gardener-guilty.webp",
      threatening: "/media/portraits/steward-threatening.webp",
    },
    defaultPortrait: "courteous",
  },
  wife: {
    id: "wife",
    name: "沈夫人",
    side: "right",
    themeColor: "#b8899a",
    voiceId: "zh-CN-XiaoyiNeural",
    portraits: {
      restrained: "/media/portraits/wife-restrained.webp",
      grieving: "/media/portraits/wife-grieving.webp",
      guarded: "/media/portraits/wife-guarded.webp",
    },
    defaultPortrait: "restrained",
  },
  gardener: {
    id: "gardener",
    name: "老周",
    side: "right",
    themeColor: "#6e9b83",
    voiceId: "zh-CN-YunjianNeural",
    portraits: {
      taciturn: "/media/portraits/gardener-taciturn.webp",
      guilty: "/media/portraits/gardener-guilty.webp",
      alarmed: "/media/portraits/gardener-alarmed.webp",
    },
    defaultPortrait: "taciturn",
  },
  accountant: {
    id: "accountant",
    name: "钱先生",
    side: "right",
    themeColor: "#7398b8",
    voiceId: "zh-CN-YunxiNeural",
    portraits: {
      composed: "/media/portraits/accountant-composed.webp",
      cornered: "/media/portraits/accountant-cornered.webp",
    },
    defaultPortrait: "composed",
  },
  painter: {
    id: "painter",
    name: "柳生",
    side: "right",
    themeColor: "#9a739f",
    portraits: {},
    defaultPortrait: "",
  },
};
