#!/usr/bin/env python3
"""Extract the GDD DOCX into reviewable Markdown without modifying the source.

The extractor intentionally uses only Python's standard library so Stage 0 can
run in a clean checkout. It preserves document-order paragraphs and tables,
maps Word heading styles to Markdown headings, and emits source metadata for
traceability.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from xml.etree import ElementTree as ET


W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
W = f"{{{W_NS}}}"


def qname(local: str) -> str:
    return f"{W}{local}"


def normalized_text(element: ET.Element) -> str:
    parts: list[str] = []
    for node in element.iter():
        if node.tag == qname("t") and node.text:
            parts.append(node.text)
        elif node.tag == qname("tab"):
            parts.append("\t")
        elif node.tag in {qname("br"), qname("cr")}:
            parts.append("\n")
    text = "".join(parts)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r" *\n *", "\n", text)
    return text.strip()


def load_heading_styles(archive: zipfile.ZipFile) -> dict[str, int]:
    try:
        root = ET.fromstring(archive.read("word/styles.xml"))
    except KeyError:
        return {}

    headings: dict[str, int] = {}
    for style in root.findall(f".//{W}style"):
        style_id = style.get(qname("styleId"), "")
        name = style.find(qname("name"))
        style_name = name.get(qname("val"), "") if name is not None else ""
        match = re.search(r"(?:heading|标题)\s*([1-9])", style_name, re.I)
        if not match:
            match = re.search(r"(?:heading|标题)([1-9])", style_id, re.I)
        if match:
            headings[style_id] = int(match.group(1))
    return headings


def paragraph_style_id(paragraph: ET.Element) -> str:
    style = paragraph.find(f"{W}pPr/{W}pStyle")
    return style.get(qname("val"), "") if style is not None else ""


def paragraph_is_list(paragraph: ET.Element) -> bool:
    return paragraph.find(f"{W}pPr/{W}numPr") is not None


def escape_table_cell(text: str) -> str:
    return text.replace("|", r"\|").replace("\n", "<br>").strip()


def table_to_markdown(table: ET.Element) -> list[str]:
    rows: list[list[str]] = []
    for row in table.findall(f"{W}tr"):
        cells = [escape_table_cell(normalized_text(cell)) for cell in row.findall(f"{W}tc")]
        if cells:
            rows.append(cells)
    if not rows:
        return []

    width = max(len(row) for row in rows)
    padded = [row + [""] * (width - len(row)) for row in rows]
    output = [
        "| " + " | ".join(padded[0]) + " |",
        "| " + " | ".join("---" for _ in range(width)) + " |",
    ]
    output.extend("| " + " | ".join(row) + " |" for row in padded[1:])
    return output


def extract_document(source: Path) -> str:
    with zipfile.ZipFile(source) as archive:
        headings = load_heading_styles(archive)
        root = ET.fromstring(archive.read("word/document.xml"))

    body = root.find(qname("body"))
    if body is None:
        raise ValueError("word/document.xml has no w:body")

    blocks: list[str] = []
    for child in body:
        if child.tag == qname("p"):
            text = normalized_text(child)
            if not text:
                continue
            style_id = paragraph_style_id(child)
            level = headings.get(style_id)
            if level is not None:
                blocks.append(f"{'#' * level} {text}")
            elif paragraph_is_list(child):
                blocks.append(f"- {text}")
            else:
                blocks.append(text)
        elif child.tag == qname("tbl"):
            table_lines = table_to_markdown(child)
            if table_lines:
                blocks.append("\n".join(table_lines))

    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    generated = datetime.now(timezone.utc).isoformat(timespec="seconds")
    header = [
        "<!--",
        "Generated from the V4.1 Source of Truth DOCX for implementation review.",
        f"Source: {source.name}",
        f"Source SHA-256: {digest}",
        f"Generated (UTC): {generated}",
        "Do not edit this file as the product Source of Truth; regenerate it from the DOCX.",
        "-->",
    ]
    return "\n".join(header) + "\n\n" + "\n\n".join(blocks) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    source = args.source.resolve()
    output = args.output.resolve()
    if source == output:
        raise ValueError("source and output must be different files")
    if not source.is_file():
        raise FileNotFoundError(source)

    markdown = extract_document(source)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8", newline="\n")
    print(f"Extracted {source.name} -> {output}")
    print(f"Characters: {len(markdown)}")


if __name__ == "__main__":
    main()
